### PR TITLE
Add test download dataset

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR does the following:

1. Add unit-tests for `donwload_dataset()`
2. Add `readr` to `Imports` in `DESCRIPTION` as the readr's, function `write_csv()` is used in `download_dataset()`
2. Add check of `limit` as logical in `get_detections()`
3. ~Refactoring, updating and in some cases simplify tests of `get_animals()` and `get_detections()` as not all of them passed~
4. Replace `%\VignetteIndexEntry{Vignette Title}` in the vignettes header should be changed to the real title as mentioned in https://bookdown.org/yihui/rmarkdown-cookbook/package-vignette.html This is needed as we have now two vignettes, otherwise error arises
5. Replace `library(tidyverse)` by explicitly naming the needed packages in vignette `etn_fields.Rmd`  and add them in `Suggests` section of file `DESCRIPTION`, if they are not already imported or suggested
6. Solve other minor problems which come out while running devtools::check(), e.g. the typical note for not finding global variables which is partially solved as always by adding `.data$` to column names in dplyr functions
7. Fix bug described in #138 
8. Fix enhancement issues #139 and #141

### CODE REVIEW

**Review by peterdesmet — CHANGES_REQUESTED** [review]
The structure of the tests for `get_detections()` and `get_animals()` are now very different from the other functions. Could you leave them unchanged in this PR, and submit those as another PR?

**Comment by damianooldoni** [comment]
I changed those tests based on what I am learning from the book about unit-testing I am reading in my freetime :nerd_face: 

Yes, making the changes in a separate PR is ok to me.

**Review by peterdesmet — CHANGES_REQUESTED** [review]
Also, `2015_homarus_detections_stubbed.csv` adds 4MB of data. I would suggest to use a zipped version of this file, or even better, the whole dataset: it will be deposited soon. I hope unzipping during the test is possible (and time efficient).

**Comment by damianooldoni** [comment]
It seems also that number of receivers and deployments has changed yesterday. I had to update the csv containing the expected output (see last commit https://github.com/inbo/etn/pull/142/commits/c2ec590e7a89c48e8aadc351a4aa89a3b03292d1).

This makes me think that this project is still open?

**Comment by damianooldoni** [comment]
@peterdesmet: I undid the changes of the unit-tests of `get_animals()` and `get_detections()`. Please, be aware that some of them will not pass now. As you suggested, I will start now a new branch for the improvement of these tests and I will make immediately after a new PR.

**Comment by damianooldoni** [comment]
About working with zip file instead of csv file, I found it is not worth working with stubbing. With a slight faster internet connection is getting detections faster than reading zip/csv files. So, I removed `mockery` and `zip` from `Suggests` in `DESCRIPTION` as not anymore needed.

**Comment by peterdesmet** [comment]
Great! No need for an included test file, just using the `download_dataset()` function.

- I have moved the message output example
- I have updated `get_animals()` and `get_detections()`test projects so they pass (will create conflict, but don't want to leave it in this state)

```
0 errors ✓ | 1 warning x | 1 note x
```

@damianooldoni you can merge this.

**Review by peterdesmet — APPROVED** [review]

**Pull request merged**
