### PR TITLE
Update funder, remove logo + custom authors

### PR DESCRIPTION
**Pull request by peterdesmet**

### CODE REVIEW

**Comment by PietrH** [comment]
If I run `pkgdown::build_site()` to have a look at the results, I modify a bunch of files. Is it safe/a good idea to commit these changes?

**Comment by PietrH** [comment]
The navbar looks very dark when I build on the VLIZ RStudio server: 

image

**Review by PietrH — CHANGES_REQUESTED** [review]
Could you have a look at the navbar? It seems dark when I build on the RStudio server (pkgdown 2.0.5)

**Comment by peterdesmet** [comment]
> Is it safe/a good idea to commit these changes?

Yes, we currently have to build and commit the website ourselves (not through GitHub Actions). And the current website has errors in all examples, so good to have it updated.

Longer term, this should be done through GitHub Actions on a `gh-pages` branch.

> Could you have a look at the navbar?

Can you install the latest version of pkgdown?

**Comment by PietrH** [comment]
> Can you install the latest version of pkgdown?

Not via `install.packages` because the latest version doesn't support R 3.6.0, I could install it via remotes but I'd have to look into why they dropped support first

**Comment by PietrH** [comment]
I was able to get it to work with `pkgdown` v2.0.9 installed via remotes;

image

**Review by PietrH — APPROVED** [review]

**Pull request merged**
