### PR TITLE
Add vignette about projectcode

### PR DESCRIPTION
**Pull request by damianooldoni**
I wrote a short tutorial about the possible confusion about project codes and project names as mentioned in #44 .

I tried to tackle the problem in the most easy way. Notice that there is still a subtle inconsistency because sometimes we have `projectname` sometimes just `name` (see #56). But I think the user would understand the concept as well.

The only thing I couldn't do is including the vignette in the html. I tried via `pkgdown::build_site()` but I don't get the page online. I think it is a problem about `pkgdown_sha:`. In fact after a `build_site()` run I get it erased to `pkgdown_sha: ~`. I tried to solve the problem, but I didn't succeded. Maybe you can give me a hint next time we meet? :+1: And maybe can you easily solve it in this PR? Thanks.

Another point: I used `knitr::kable()` as you did in `access-etn-data.Rmd`. I am just wondering if such code line would not be confusing for the typical R user. Actually it is just a functional commando for making the tutorial appearance nicer.

Here below a first idea to make both code chunk and html nice:
- Use `eval = FALSE` in the code chunk **without** `knitr::kable()` at the end
- Use `echo = FALSE` in the same code chunk **with** `knitr::kable()` at the end

If you think I am right but you think it is better to tackle afterwards in a separate branch afterwards, I agree totally with you.

### CODE REVIEW

**Comment by peterdesmet** [comment]
Best to include your df print option (e.g. `kable`) in the yaml settings of the Rmd, rather than in the code.

**Comment by peterdesmet** [comment]
Did a quick review, and I have updated the vignette file names and updated their title:

- etn-overview: Introduction to main functions of the ETN package
- access-project-info: Get project information

@damianooldoni can you rebuild the site on the Rstudio server?

@damianooldoni note: the reason why your vignette was not included in the menu, is because you edited `docs/pkgdown.yml`. You have to edit `_pkgdown.yml` in the root, which is the source file. Good rule of thumb: never manually edit anything in docs.

**Comment by damianooldoni** [comment]
Thanks @peterdesmet for your help and suggestions! I rebuild the site.

**Comment by damianooldoni** [comment]
Yes, it works. I rebuilt the site correctly. 
The only thing is the absence of a key now at `pkgdown_sha: ~`.
@stijnvanhoey: does it have something to do with Travis CI?

**Comment by stijnvanhoey** [comment]
@damianooldoni you shouldn't be worried about the sha...  Notice that there is no travis setup for this repo, as we can not provide the data access outside the VLIZ Rstudio server environment.

**Comment by stijnvanhoey** [comment]
and +1 for adding the kable as yaml setting instead of individual chunk settings, cfr.

try with an adapt of the YAML headers:
```
output: rmarkdown::html_vignette
  html_document:
    df_print: paged
```
(we use paged instead of kable)

**Comment by peterdesmet** [comment]
I didn’t check the output, but maybe the dataframes are too small to be paged? Do they look different than regular boring df print?

**Comment by damianooldoni** [comment]
Well, now they are quite similar to the output you get on a console...

**Comment by stijnvanhoey** [comment]
- I've tested adding the config on level of `_pkgdown` (as done in Rmarkdwon webpage)  ->no effect
- adapting  the yaml header options -> no effect
...

**Comment by peterdesmet** [comment]
This vignette is no longer necessary, see https://github.com/inbo/etn/issues/44#issuecomment-589728136

Regarding nicer table printing, we'll have to figure that out for the main vignette anyway, so I'm on it.

**Pull request closed without merging**
