### PR TITLE
Add function list values

### LINKED ISSUE #183: Helper function to pull unique lists
I often want a unique list of items from my selection, e.g. get the tag_serial_numbers associated with my animals:

```R
tag_serial_numbers <- get_animals() %>% distinct(tag_serial_number) %>% pull() # a vector
```

I can use that vector to do:

```R
get_acoustic_tags(tag_serial_number = tag_serial_numbers)
```

@jreubens @PieterjanVerhelst @damianooldoni Would it be useful to have a helper function for this:

```R
get_animals() %>% extract(tag_serial_number) # a vector
```

Note that this function could have build-in functionality to deal with multiple comma separated values:

```
"A,B", "C" -> c("A", "B", "C")
```

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR should fix #183 by adding a support function called `list_values()`. As this function is a helper, I put it in `zzz.R` and I don't expose its documentation: same behavior of all other functions in such file.

The function accepts an unquoted column name as asked by @peterdesmet (tidyverse style, e.g. `column = tag_serial_number`) but also a character with the column name  (quoted column name,  e.g. `column = "tag_serial_number"`) or a column position (e.g. `column = 2` for the second column). The function can be used combined with a pipe as well, again as described in #183.

Extensive testing added in `test-list_values.R`

### CODE REVIEW

**Comment by peterdesmet** [comment]
@damianooldoni I haven't tested yet, but could you already:

- Move this function to its own file `list_values()`. It is more than a helper function, since users (and not only functions) will make use of it. It's documentation should be available as well, cf. other `list_` functions.
- Would it be possible to have the function message the number of unique values it finds, or will that mess up pipe functions?

```R
tag_serial_numbers <- get_animals() %>% list_values(tag_serial_number)
#> 94 unique tag_serial_number values
```

**Comment by damianooldoni** [comment]
No, informative message has nothing to do with piping. 👍 
Your requests are implemented.

**Review by peterdesmet — APPROVED** [review]
Made some changes to the function documentation and the way the tests are written. The example is now a real ETN example, which I hope will inform users how useful it is.

**Comment by peterdesmet** [comment]
I will merge this PR in the ongoing sql_views branch.

**Comment by peterdesmet** [comment]
Thanks for creating this function @damianooldoni 👍

**Pull request merged**
